// <auto-generated />
using System;
using AutoSale.Payments.Mock.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoSale.Payments.Mock.Persistence.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    partial class PaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AutoSale.Payments.Mock.Payments.Payment", b =>
                {
                    b.Property<Guid>("PaymentCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_code");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempts");

                    b.Property<long?>("CallbackDeliveredAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("callback_delivered_at_utc");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<long?>("LeaseExpiresAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("lease_owner");

                    b.Property<long?>("NextAttemptAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<long?>("OccurredAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("PaymentCode");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.HasIndex("CallbackDeliveredAtUtc", "NextAttemptAtUtc");

                    b.ToTable("payments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
