// <auto-generated />
using System;
using AutoSale.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoSale.Sales.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260908133523_InitialSalesSchema")]
    partial class InitialSalesSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoSale.Domain.Catalog.VehicleCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model");

                    b.Property<decimal>("Price")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at_utc");

                    b.Property<int>("SourceVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("source_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synchronized_at_utc");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Price", "Id")
                        .HasDatabaseName("ix_vehicle_catalog_status_price_id");

                    b.ToTable("vehicle_catalog", (string)null);
                });

            modelBuilder.Entity("AutoSale.Domain.Payments.PaymentCallback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_code");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_callbacks_event_id");

                    b.ToTable("payment_callbacks", (string)null);
                });

            modelBuilder.Entity("AutoSale.Domain.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("BuyerSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("buyer_subject");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("ExpectedPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("expected_price");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("failure_code");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<Guid>("PaymentCode")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_code");

                    b.Property<DateTimeOffset?>("PaymentOccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_occurred_at_utc");

                    b.Property<DateTimeOffset?>("PaymentRegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_registered_at_utc");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("request_hash");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("sale_price");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PaymentCode")
                        .IsUnique()
                        .HasDatabaseName("ux_sales_payment_code");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ux_sales_active_vehicle")
                        .HasFilter("\"state\" NOT IN ('Cancelled', 'Rejected')");

                    b.HasIndex("BuyerSubject", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_sales_buyer_idempotency");

                    b.HasIndex("SalePrice", "Id")
                        .HasDatabaseName("ix_sales_completed_price_id")
                        .HasFilter("\"state\" = 'Completed'");

                    b.HasIndex("State", "NextAttemptAtUtc", "LeaseExpiresAtUtc")
                        .HasDatabaseName("ix_sales_pending_claim");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("AutoSale.Domain.Sales.Sale", b =>
                {
                    b.OwnsOne("AutoSale.Domain.Buyers.BuyerCpf", "BuyerCpf", b1 =>
                        {
                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("buyer_cpf");

                            b1.HasKey("SaleId");

                            b1.ToTable("sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.OwnsOne("AutoSale.Domain.Sales.VehicleSnapshot", "VehicleSnapshot", b1 =>
                        {
                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("snapshot_color");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("snapshot_vehicle_id");

                            b1.Property<string>("Make")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("snapshot_make");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("snapshot_model");

                            b1.Property<decimal>("Price")
                                .HasPrecision(14, 2)
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("snapshot_price");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("snapshot_status");

                            b1.Property<DateTimeOffset>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("snapshot_updated_at_utc");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("snapshot_version");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("snapshot_year");

                            b1.HasKey("SaleId");

                            b1.ToTable("sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.Navigation("BuyerCpf")
                        .IsRequired();

                    b.Navigation("VehicleSnapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
